-- View: public.vw_att_details_cable

-- DROP VIEW public.vw_att_details_cable;

CREATE OR REPLACE VIEW public.vw_att_details_cable
 AS
 SELECT cable.system_id,
    cable.network_id,
    cable.cable_name,
    fn_get_display_name(cable.a_system_id, cable.a_entity_type) AS a_location,
    fn_get_display_name(cable.b_system_id, cable.b_entity_type) AS b_location,
    cable.total_core,
    cable.no_of_tube,
    cable.no_of_core_per_tube,
    round(cable.cable_measured_length::numeric, 2) AS cable_measured_length,
    round(cable.cable_calculated_length::numeric, 2) AS cable_calculated_length,
    cable.cable_type,
    cable.coreaccess,
    cable.wavelength,
    cable.optical_output_power,
    cable.frequency,
    cable.attenuation_db,
    cable.resistance_ohm,
    cable.construction,
    cable.activation,
    cable.accessibility,
    cable.specification,
    cable.category,
    cable.subcategory1,
    cable.subcategory2,
    cable.subcategory3,
    cable.item_code,
    cable.vendor_id,
    cable.type,
    cable.brand,
    cable.model,
    cable.network_status,
    cable.status,
    cable.pin_code,
    cable.province_id,
    cable.region_id,
    cable.utilization,
    cable.totalattenuationloss,
    cable.chromaticdb,
    cable.chromaticdispersion,
    cable.totalchromaticloss,
    cable.remarks,
    cable.route_id,
    cable.created_by,
    cable.created_on,
    cable.modified_by,
    cable.modified_on,
    cable.a_system_id,
    cable.a_entity_type,
    cable.b_system_id,
    cable.b_entity_type,
    cable.sequence_id,
    cable.duct_id,
    cable.trench_id,
    cable.project_id,
    cable.planning_id,
    cable.purpose_id,
    cable.workorder_id,
    cable.structure_id,
    cable.cable_category,
    cable.execution_method,
    prov.province_name,
    reg.region_name,
    um.user_name,
    vm.name AS vendor_name,
    tp.type AS cable_specification_type,
    bd.brand AS cable_brand,
    ml.model AS cable_model,
    cable.total_loop_count,
    cable.total_loop_length,
    fn_get_date(cable.created_on) AS created_date,
    fn_get_date(cable.modified_on) AS modified_date,
    um.user_name AS created_by_user,
    um2.user_name AS modified_by_user,
    cable.parent_system_id,
    cable.parent_entity_type,
    cable.parent_network_id,
    round(cable.start_reading::numeric, 2) AS start_reading,
    round(cable.end_reading::numeric, 2) AS end_reading,
    cable.cable_sub_category,
    cable.acquire_from,
    cable.circuit_id,
    cable.thirdparty_circuit_id,
    cable.drum_no,
    ( SELECT system_spec_master.prop_name
           FROM system_spec_master
          WHERE system_spec_master.id = cable.accessibility) AS cable_accessibility,
    ( SELECT system_spec_master.prop_name
           FROM system_spec_master
          WHERE system_spec_master.id = cable.construction) AS cable_construction,
    ( SELECT system_spec_master.prop_name
           FROM system_spec_master
          WHERE system_spec_master.id = cable.activation) AS cable_activation,
    cable.barcode,
    cable.ownership_type,
    vm2.id AS third_party_vendor_id,
    vm2.name AS third_party_vendor_name,
    cable.source_ref_type,
    cable.source_ref_id,
    cable.source_ref_description,
    cable.status_remark,
    cable.status_updated_by,
    cable.status_updated_on,
    cable.is_visible_on_map,
    cable.primary_pod_system_id,
    cable.secondary_pod_system_id,
    cable.is_new_entity,
    round(cable.inner_dimension::numeric, 2) AS inner_dimension,
    round(cable.outer_dimension::numeric, 2) AS outer_dimension,
    cable.calculated_length_remark,
    cable.audit_item_master_id,
    cable.is_acquire_from,
    cable.origin_from,
    cable.origin_ref_id,
    cable.origin_ref_code,
    cable.origin_ref_description,
    cable.request_ref_id,
    cable.requested_by,
    cable.request_approved_by,
    cable.subarea_id,
    cable.area_id,
    cable.dsa_id,
    cable.csa_id,
    cable.bom_sub_category,
    cable.gis_design_id,
    cable.ne_id,
    cable.prms_id,
    cable.jc_id,
    cable.mzone_id,
    cable.a_location_name,
    cable.b_location_name,
    cable.route_name,
    cable.hierarchy_type,
    cable.section_name,
    cable.aerial_location,
    cable.cable_remark,
    cable.generic_section_name,
    cable.own_vendor_id,
    cable.manhole_count
   FROM att_details_cable cable
     JOIN province_boundary prov ON cable.province_id = prov.id
     JOIN region_boundary reg ON cable.region_id = reg.id
     JOIN user_master um ON cable.created_by = um.user_id
     JOIN vendor_master vm ON cable.vendor_id = vm.id
     LEFT JOIN vendor_master vm2 ON cable.third_party_vendor_id = vm2.id
     LEFT JOIN isp_type_master tp ON cable.type = tp.id
     LEFT JOIN isp_brand_master bd ON cable.brand = bd.id
     LEFT JOIN isp_base_model ml ON cable.model = ml.id
     LEFT JOIN user_master um2 ON cable.modified_by = um2.user_id;

ALTER TABLE public.vw_att_details_cable
    OWNER TO postgres;

