CREATE OR REPLACE FUNCTION public.fn_get_near_by_route(
	p_geom character varying)
    RETURNS SETOF json 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$


DECLARE V_BUFFER_GEOMETRY GEOMETRY ;
V_GEOMETRY GEOMETRY;
BEGIN

SELECT ST_GEOMFROMTEXT('POINT('||p_geom||')', 4326) INTO V_GEOMETRY;

IF(COALESCE(V_GEOMETRY::text,'')!='')
THEN
	V_BUFFER_GEOMETRY:=ST_BUFFER_METERS(V_GEOMETRY,5);


	RETURN QUERY SELECT ROW_TO_JSON(ROW) FROM (
		SELECT CBL.SYSTEM_ID AS CABLE_ID,CBL.NETWORK_ID AS ENTITY_NETWORK_ID,CBL.ROUTE_ID,false IS_ASSOCIATED
		FROM LINE_MASTER LM 
		INNER JOIN ATT_DETAILS_CABLE CBL on LM.ENTITY_TYPE='Cable' AND ST_INTERSECTS(LM.SP_GEOMETRY,V_BUFFER_GEOMETRY) AND CBL.SYSTEM_ID=LM.SYSTEM_ID
	) ROW;
END IF;
END
$BODY$;

ALTER FUNCTION public.fn_get_near_by_route(character varying)
    OWNER TO postgres;