CREATE OR REPLACE FUNCTION public.fn_splicing_validate_connection_mobile(p_entitytype character varying, p_systemid integer, p_from integer, p_to integer)
 RETURNS TABLE(status boolean, message character varying)
 LANGUAGE plpgsql
AS $function$
declare
v_status boolean;
v_message character varying;
v_layer_table character varying;
v_totalcore integer;
v_connected_cores integer;
AROW record;

BEGIN
v_status:=true;
v_message:=null;

SELECT LAYER_TABLE INTO V_LAYER_TABLE FROM LAYER_DETAILS WHERE UPPER(LAYER_NAME)=UPPER(P_ENTITYTYPE);

IF(UPPER(P_ENTITYTYPE)='CABLE') THEN

	EXECUTE 'SELECT TOTAL_CORE FROM '||V_LAYER_TABLE||' WHERE SYSTEM_ID='||P_SYSTEMID||'' INTO V_TOTALCORE;

	--CHECKING SOURCE RANGE IS MATCHING CABLE CORE OR NOT
	SELECT COUNT(*) INTO V_CONNECTED_CORES FROM ATT_DETAILS_CABLE_INFO  WHERE CABLE_ID=P_SYSTEMID AND FIBER_NUMBER=P_FROM;

	IF(V_CONNECTED_CORES =0) THEN
	V_STATUS:=FALSE;
	v_message='Source range can not be greater than total cable cores!';
	RETURN QUERY
	SELECT V_STATUS AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
	END IF;

	--CHECKING DESTINATION RANGE IS MATCHING CABLE CORE OR NOT
	SELECT COUNT(*) INTO V_CONNECTED_CORES FROM ATT_DETAILS_CABLE_INFO  WHERE CABLE_ID=P_SYSTEMID AND FIBER_NUMBER=P_TO;

	IF(V_CONNECTED_CORES =0) THEN
	V_STATUS:=FALSE;
	v_message='Destination range can not be greater than total cable cores!';
	RETURN QUERY
	SELECT V_STATUS AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
	END IF;

	--CHECKING IF CABLE CORE IS ALREADY SPLICED OR NOT

	SELECT COUNT(1)INTO V_CONNECTED_CORES FROM ATT_DETAILS_CABLE_INFO  WHERE CABLE_ID=P_SYSTEMID AND A_END_STATUS_ID=2 AND (FIBER_NUMBER=P_FROM OR FIBER_NUMBER=P_TO);

	IF(V_CONNECTED_CORES=2) THEN
	V_STATUS:=FALSE;
	v_message='Already connected for this range!';
	RETURN QUERY
	SELECT V_STATUS AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
	END IF;

	--CHECKING IF ALL CABLE CORE IS SPLICED OR NOT

	SELECT COUNT(*) INTO V_CONNECTED_CORES FROM ATT_DETAILS_CABLE_INFO  WHERE CABLE_ID=P_SYSTEMID AND A_END_STATUS_ID=2;
	
	IF(V_CONNECTED_CORES=V_TOTALCORE) THEN
	V_STATUS:=FALSE;
	v_message='All cable cores are occupied!';
	RETURN QUERY
	SELECT V_STATUS AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
	END IF;


ELSIF(UPPER(P_ENTITYTYPE) = 'FMS') THEN

	EXECUTE 'SELECT NO_OF_PORT FROM '||V_LAYER_TABLE||' WHERE SYSTEM_ID='||P_SYSTEMID||'' INTO V_TOTALCORE;

	raise info 'V_TOTALCORE%',V_TOTALCORE;
	
	--CHECKING SOURCE RANGE IS MATCHING FMS PORT OR NOT

	SELECT COUNT(*) INTO V_CONNECTED_CORES FROM ISP_PORT_INFO WHERE PARENT_SYSTEM_ID=P_SYSTEMID AND UPPER(PARENT_ENTITY_TYPE)=UPPER(P_ENTITYTYPE) 
	AND PORT_STATUS_ID=P_FROM AND INPUT_OUTPUT='I';

	IF(V_CONNECTED_CORES=0) THEN
	V_STATUS:=FALSE;
	v_message='Source range can not be greater than total ports!';
	RETURN QUERY
	SELECT V_STATUS AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
	END IF;

	--CHECKING DESTINATION RANGE IS MATCHING FMS PORT OR NOT
	SELECT COUNT(*) INTO V_CONNECTED_CORES FROM ISP_PORT_INFO WHERE PARENT_SYSTEM_ID=P_SYSTEMID AND UPPER(PARENT_ENTITY_TYPE)=UPPER(P_ENTITYTYPE)
	AND PORT_NUMBER=P_TO AND INPUT_OUTPUT='O';


	IF(V_CONNECTED_CORES =0) THEN
	V_STATUS:=FALSE;
	v_message='Destination range can not be greater than total ports!';
	RETURN QUERY
	SELECT V_STATUS AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
	END IF;

	--CHECKING IF FMS PORT IS ALREADY SPLICED OR NOT
	
	SELECT COUNT(1) INTO V_CONNECTED_CORES FROM ISP_PORT_INFO WHERE PARENT_SYSTEM_ID=P_SYSTEMID AND UPPER(PARENT_ENTITY_TYPE)=('FMS') AND INPUT_OUTPUT='O' AND PORT_STATUS_ID=2 
	AND (PORT_NUMBER=P_FROM OR PORT_NUMBER=P_TO);

	IF(V_CONNECTED_CORES=2) THEN
	V_STATUS:=FALSE;
	v_message='Already connected for this range!';
	RETURN QUERY
	SELECT V_STATUS AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
	END IF;

	--CHECKING IF ALL FMS PORT IS SPLICED OR NOT
	
	SELECT COUNT(*) INTO V_CONNECTED_CORES FROM ISP_PORT_INFO WHERE PARENT_SYSTEM_ID=P_SYSTEMID AND UPPER(PARENT_ENTITY_TYPE)=UPPER(P_ENTITYTYPE) 
	AND INPUT_OUTPUT='O' AND PORT_STATUS_ID=2;
	
	IF(V_CONNECTED_CORES=V_TOTALCORE) THEN
	V_STATUS:=FALSE;
	v_message='All ports are occupied';
	RETURN QUERY
	SELECT V_STATUS AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
	END IF;

ELSE
	RETURN QUERY
	select true as status,''::character varying as message;
END IF;

END; $function$
;