UPDATE PROVINCE_BOUNDARY
SET PROVINCE_ABBREVIATION = REPLACE(PROVINCE_ABBREVIATION, chr(10), '')
WHERE PROVINCE_ABBREVIATION LIKE '%' || chr(10) || '%';
-------------------------------------------------------
update data_uploader_column_mapping set imported_column_name='network_status' where template_db_column_name='network_status' and template_id =6;

update data_uploader_template set template_column_name='network_status' where db_column_name='network_status' and layer_id =14;
---------------------------------------------
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('de-DE', 'SI_OSP_GBL_NET_RPT_417', 'Link Id prefix does not exist in the Link Prefix dropdown!', false, true, 'German', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:00:49.335', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('en', 'SI_OSP_GBL_NET_RPT_417', 'Link Id prefix does not exist in the Link Prefix dropdown!', true, true, 'English', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:00:49.335', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('fr', 'SI_OSP_GBL_NET_RPT_417', 'Link Id prefix does not exist in the Link Prefix dropdown!', false, true, 'French', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:00:49.335', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('hi', 'SI_OSP_GBL_NET_RPT_417', 'Link Id prefix does not exist in the Link Prefix dropdown!', false, true, 'Hindi', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:00:49.335', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('ja-JP', 'SI_OSP_GBL_NET_RPT_417', 'Link Id prefix does not exist in the Link Prefix dropdown!', false, true, 'Japanese', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:00:49.335', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('ru-RU', 'SI_OSP_GBL_NET_RPT_417', 'Link Id prefix does not exist in the Link Prefix dropdown!', false, true, 'Russian', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:00:49.335', 5, true, false);


INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('de-DE', 'SI_OSP_GBL_NET_RPT_418', 'Link Id prefix must match with Link Prefix!', false, true, 'German', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:02:56.708', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('en', 'SI_OSP_GBL_NET_RPT_418', 'Link Id prefix must match with Link Prefix!', true, true, 'English', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:02:56.708', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('fr', 'SI_OSP_GBL_NET_RPT_418', 'Link Id prefix must match with Link Prefix!', false, true, 'French', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:02:56.708', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('hi', 'SI_OSP_GBL_NET_RPT_418', 'Link Id prefix must match with Link Prefix!', false, true, 'Hindi', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:02:56.708', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('ja-JP', 'SI_OSP_GBL_NET_RPT_418', 'Link Id prefix must match with Link Prefix!', false, true, 'Japanese', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:02:56.708', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('ru-RU', 'SI_OSP_GBL_NET_RPT_418', 'Link Id prefix must match with Link Prefix!', false, true, 'Russian', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-10 13:02:56.708', 5, true, false);
