
TRUNCATE table fiber_link_columns_settings;

INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(1, 'network_id', 1, 'Network Id', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_OSP_GBL_NET_RPT_070', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(2, 'link_id', 2, 'Link/Route Id', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_153', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(3, 'link_name', 3, 'Link/Route Name', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_127', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(4, 'start_point_type', 4, 'Start Point Type', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_128', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(5, 'start_point_network_id', 5, 'Start Point Network Id', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_129', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(6, 'start_point_location', 6, 'Start Point Location', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_130', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(7, 'end_point_type', 7, 'End Point Type', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_131', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(8, 'end_point_network_id', 8, 'End Point Network Id', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_132', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(9, 'end_point_location', 9, 'End Point Location', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_133', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(10, 'no_of_lmc', 10, 'No. Of LMC', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_134', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(11, 'each_lmc_length', 11, 'Each LMC Length(Mtr.)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_135', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(12, 'total_route_length', 12, 'Total Route Length(Mtr.)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_136', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(13, 'gis_length', 13, 'GIS Length(Mtr.)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_137', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(14, 'otdr_distance', 14, 'OTDR Distance(Mtr.)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_138', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(15, 'no_of_pair', 15, 'No. Of Pairs', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_141', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(16, 'tube_and_core_details', 16, 'Tube And Core Details', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_142', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(17, 'existing_route_length_otdr', 17, 'Existing Route Length(OTDR)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_143', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(18, 'new_building_route_length', 18, 'New Build Route Length(Mtr.)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_144', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(19, 'otm_length', 19, 'OTM Length(Mtr.)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_145', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(20, 'otl_length', 20, 'OTL Length(Mtr.)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_146', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(21, 'Any_row_portion', 21, 'Any ROW Portion', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_147', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(22, 'row_authority', 22, 'ROW Authority', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_148', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(23, 'total_row_segments', 23, 'Total ROW Segments', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_149', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(24, 'total_row_length', 24, 'Total ROW Length(Mtr.)', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_150', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(25, 'total_row_reccuring_charges', 25, 'Total ROW Recurring Charges/Annum({0})', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_151', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(26, 'handover_date', 26, 'Handover Date', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_139', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(27, 'hoto_signoff_date', 27, 'HOTO Signoff Date', true, 1, '2020-12-04 17:58:54.061', NULL, NULL, 'SI_GBL_GBL_NET_FRM_140', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(29, 'created_by', 29, 'Created By', true, 1, '2020-12-04 18:35:35.757', NULL, NULL, 'SI_OSP_GBL_GBL_GBL_056', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(30, 'created_on', 30, 'Created On', true, 1, '2020-12-04 18:35:35.757', NULL, NULL, 'SI_OSP_GBL_GBL_GBL_055', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(31, 'modified_by', 31, 'Modified By', true, 1, '2020-12-04 18:35:35.757', NULL, NULL, 'SI_OSP_GBL_GBL_GBL_058', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(32, 'modified_on', 32, 'Modified On', true, 1, '2020-12-04 18:35:35.757', NULL, NULL, 'SI_OSP_GBL_GBL_GBL_057', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(33, 'fiber_link_status', 33, 'Fiber Link Status', true, 1, '2020-12-04 18:36:13.511', NULL, NULL, 'SI_OSP_GBL_GBL_GBL_148', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(34, 'end_point_longitude', 34, 'End Point Longitude', true, 1, NULL, NULL, NULL, NULL, false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(35, 'start_point_longitude', 35, 'Start Point Longitude', true, 1, NULL, NULL, NULL, NULL, false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(36, 'link_type', 36, 'Link Type', true, 1, '2021-04-22 16:56:24.164', NULL, NULL, 'SI_OSP_GBL_GBL_GBL_155', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(37, 'service_id', 37, 'Service Id', true, 1, '2021-09-30 12:14:06.870', NULL, NULL, 'SI_OSP_GBL_GBL_FRM_102', true);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(38, 'end_point_latitude', 38, 'End Point Latitude', true, 1, NULL, NULL, NULL, NULL, false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(39, 'main_link_type', 39, 'Main Link Type', true, 1, '2022-02-03 18:40:23.613', NULL, NULL, 'SI_OSP_GBL_GBL_FRM_206', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(40, 'main_link_id', 40, 'Main Link Id', true, 1, '2022-02-03 18:40:23.667', NULL, NULL, 'SI_OSP_GBL_NET_GBL_190', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(41, 'redundant_link_type', 41, 'Redundant Link Type', true, 1, '2022-02-03 18:40:23.699', NULL, NULL, 'SI_OSP_GBL_NET_GBL_191', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(42, 'redundant_link_id', 42, 'Redundant Link Id', true, 1, '2022-02-03 18:40:23.730', NULL, NULL, 'SI_OSP_GBL_NET_GBL_192', false);
INSERT INTO public.fiber_link_columns_settings (id, column_name, column_sequence, display_name, is_active, created_by, created_on, modified_by, modified_on, res_field_key, is_kml_column) VALUES(43, 'start_point_latitude', 43, 'Start Point Latitude', true, 1, NULL, NULL, NULL, NULL, false);



