update global_settings set value=10 where key='MaxFileCountLimit'

--------------
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('de-DE', 'SI_OSP_GBL_NET_GBL_289', 'Only maxFileCountLimit files are allowed to upload!', false, true, 'German', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-27 15:32:03.923', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('en', 'SI_OSP_GBL_NET_GBL_289', 'Only maxFileCountLimit files are allowed to upload!', true, true, 'English', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-27 15:32:03.923', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('fr', 'SI_OSP_GBL_NET_GBL_289', 'Only maxFileCountLimit files are allowed to upload!', false, true, 'French', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-27 15:32:03.923', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('hi', 'SI_OSP_GBL_NET_GBL_289', 'Only maxFileCountLimit files are allowed to upload!', false, true, 'Hindi', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-27 15:32:03.923', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('ja-JP', 'SI_OSP_GBL_NET_GBL_289', 'Only maxFileCountLimit files are allowed to upload!', false, true, 'Japanese', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-27 15:32:03.923', 5, true, false);
INSERT INTO public.res_resources (culture, "key", value, is_default_lang, is_visible, "language", description, modified_by, modified_on, created_on, created_by, is_jquery_used, is_mobile_key) VALUES('ru-RU', 'SI_OSP_GBL_NET_GBL_289', 'Only maxFileCountLimit files are allowed to upload!', false, true, 'Russian', 'Smart Inventory_Osp_Global_Dot Net_', NULL, NULL, '2024-12-27 15:32:03.923', 5, true, false);

----------------------
update global_settings set value=10 where key='AdddocumentRowNumber'