update dropdown_master set dropdown_value='AC' where dropdown_key='Access' and layer_id=(select layer_id from layer_details where layer_name='Trench') and dropdown_type='trench_serving_type';
update dropdown_master set dropdown_value='ACLM' where dropdown_key='Access LM' and layer_id=(select layer_id from layer_details where layer_name='Trench') and dropdown_type='trench_serving_type';
update dropdown_master set dropdown_value='BB' where dropdown_key='Backbone' and layer_id=(select layer_id from layer_details where layer_name='Trench') and dropdown_type='trench_serving_type';
update dropdown_master set dropdown_value='BBLM' where dropdown_key='Backbone LM' and layer_id=(select layer_id from layer_details where layer_name='Trench') and dropdown_type='trench_serving_type';


UPDATE VENDOR_MASTER SET ABBR='ID' WHERE UPPER(NAME)='E-IDEA';
UPDATE VENDOR_MASTER SET ABBR='VF' WHERE UPPER(NAME)='E-VODAFONE';
UPDATE VENDOR_MASTER SET ABBR='VI' WHERE UPPER(NAME)='VITIL';
UPDATE VENDOR_MASTER SET ABBR='AI' WHERE UPPER(NAME)='AIRTEL';
UPDATE VENDOR_MASTER SET ABBR='RJ' WHERE UPPER(NAME)='R-JIO';
UPDATE VENDOR_MASTER SET ABBR='TT' WHERE UPPER(NAME)='TTSL';
UPDATE VENDOR_MASTER SET ABBR='TC' WHERE UPPER(NAME)='TCL';
UPDATE VENDOR_MASTER SET ABBR='RC' WHERE UPPER(NAME)='R-COM';
UPDATE VENDOR_MASTER SET ABBR='DP' WHERE UPPER(NAME)='DEPL';
UPDATE VENDOR_MASTER SET ABBR='VT' WHERE UPPER(NAME)='VTL';
UPDATE VENDOR_MASTER SET ABBR='OW' WHERE UPPER(NAME)='OPGW/UTILITY';
UPDATE VENDOR_MASTER SET ABBR='OT' WHERE UPPER(NAME)='OTHER IP1';

Update res_resources set value='Section ID' where key='SI_GBL_GBL_GBL_GBL_164';

Update res_resources set value='Section id will be updated. Do you want to continue?' where key='SI_OSP_GBL_JQ_FRM_191';


INSERT INTO public.layer_action_mapping(
	layer_id, action_name, is_active, action_sequence, action_title, is_visible, is_isp_action, is_osp_action, action_abbr, action_layer_id, action_module_id, is_mobile_action, is_web_action, action_mobile_module_id, res_field_key, is_enable_in_draft, parent_action_id)
select layer_id, 'UpdateGeographicDetails', is_active, (select max(action_sequence)+1 from layer_action_mapping where layer_id=(select layer_id from layer_details where layer_name='Cable')), 'Create route id', is_visible, is_isp_action, is_osp_action, action_abbr, action_layer_id, action_module_id, is_mobile_action, is_web_action, action_mobile_module_id, '', is_enable_in_draft, parent_action_id from layer_action_mapping where layer_id=(select layer_id from layer_details where layer_name='Cable') and action_name='History';




CREATE OR REPLACE FUNCTION public.fn_create_route_id(
	p_system_id integer,
	p_entity_type character varying,
	p_associate_system_id integer,
	p_associate_entity_type character varying)
    RETURNS TABLE(status boolean, routeid character varying) 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$


DECLARE V_SEQUENCE INTEGER;
V_ENTITY_CODE CHARACTER VARYING;
V_PROVINCE_ID INTEGER;
V_CICRCLE_CODE CHARACTER VARYING;
V_BUILD_TYPE CHARACTER VARYING;
V_BUILD_BY CHARACTER VARYING;
V_ENTITY_T CHARACTER VARYING;
V_A_END_CODE CHARACTER VARYING;
V_B_END_CODE CHARACTER VARYING;
V_SQL TEXT;
V_LAYER_TABLE CHARACTER VARYING;
V_GEOM_TABLE CHARACTER VARYING;
V_STATUS BOOLEAN=TRUE;
V_ROUTE_ID CHARACTER VARYING;
V_A_END_SYSTEM_ID INTEGER;
V_A_END_ENTITY_TYPE CHARACTER VARYING;
V_B_END_SYSTEM_ID INTEGER;
V_B_END_ENTITY_TYPE CHARACTER VARYING;
V_STARTPOINT GEOMETRY;
V_ENDPOINT GEOMETRY;
V_DESIGN_ID CHARACTER VARYING;
V_COUNT INTEGER;
V_CHAMBER_T CHARACTER VARYING='LM001';
BEGIN

SELECT LAYER_TABLE,GEOM_TYPE||'_MASTER' INTO V_LAYER_TABLE,V_GEOM_TABLE FROM LAYER_DETAILS WHERE UPPER(LAYER_NAME)=UPPER(P_ENTITY_TYPE);

V_SQL='SELECT COUNT(1) FROM '|| V_LAYER_TABLE ||' WHERE SYSTEM_ID='|| P_SYSTEM_ID ||' AND COALESCE(GIS_DESIGN_ID,'''')!=''''';
EXECUTE V_SQL INTO V_COUNT;

IF(COALESCE(V_COUNT,0)>0)
THEN
V_STATUS=FALSE;
ELSE

V_SQL='SELECT P.PROVINCE_ABBREVIATION,P.ID FROM '|| V_LAYER_TABLE ||' ATT
INNER JOIN PROVINCE_BOUNDARY P ON ATT.PROVINCE_ID=P.ID WHERE ATT.SYSTEM_ID='|| P_SYSTEM_ID ||'';
EXECUTE V_SQL INTO V_CICRCLE_CODE,V_PROVINCE_ID;

SELECT LAYER_ABBREVATION INTO V_ENTITY_CODE FROM CODIFICATION_LAYER_DETAILS WHERE UPPER(LAYER_NAME)=UPPER(P_ENTITY_TYPE);

IF(UPPER(P_ENTITY_TYPE) IN ('CABLE','DUCT','TRENCH'))
THEN

V_SQL='SELECT ' || CASE WHEN UPPER(P_ENTITY_TYPE)='CABLE' THEN 'COALESCE(CABLE_CATEGORY,'''')' WHEN UPPER(P_ENTITY_TYPE)='DUCT' THEN 'COALESCE(DUCT_TYPE,'''')' else 'COALESCE(TRENCH_SERVING_TYPE,'''')' END ||'
,COALESCE(A_LOCATION_CODE,''''),COALESCE(B_LOCATION_CODE,'''') FROM '|| V_LAYER_TABLE ||' WHERE SYSTEM_ID='|| P_SYSTEM_ID ||'';
EXECUTE V_SQL INTO V_ENTITY_T,V_A_END_CODE,V_B_END_CODE;

SELECT ST_BUFFER_METERS(ST_STARTPOINT(SP_GEOMETRY),2) INTO V_STARTPOINT FROM LINE_MASTER WHERE UPPER(ENTITY_TYPE)=UPPER(P_ENTITY_TYPE) AND SYSTEM_ID=P_SYSTEM_ID;
SELECT ST_BUFFER_METERS(ST_ENDPOINT(SP_GEOMETRY),2) INTO V_ENDPOINT FROM LINE_MASTER WHERE UPPER(ENTITY_TYPE)=UPPER(P_ENTITY_TYPE) AND SYSTEM_ID=P_SYSTEM_ID;

SELECT SYSTEM_ID,ENTITY_TYPE INTO V_A_END_SYSTEM_ID,V_A_END_ENTITY_TYPE FROM POINT_MASTER WHERE
ST_INTERSECTS(V_STARTPOINT,SP_GEOMETRY) AND UPPER(ENTITY_TYPE) IN ('FMS','MANHOLE') LIMIT 1;

SELECT SYSTEM_ID,ENTITY_TYPE INTO V_B_END_SYSTEM_ID,V_B_END_ENTITY_TYPE FROM POINT_MASTER WHERE
ST_INTERSECTS(V_ENDPOINT,SP_GEOMETRY) AND UPPER(ENTITY_TYPE) IN ('FMS','MANHOLE') LIMIT 1;

V_SQL='SELECT MAX(COALESCE(CODIFICATION_SEQUENCE,0))+1 FROM '|| V_LAYER_TABLE ||'
WHERE A_LOCATION_CODE='''|| V_A_END_CODE ||''' AND B_LOCATION_CODE='''|| V_B_END_CODE ||''' GROUP BY A_LOCATION_CODE,B_LOCATION_CODE';
EXECUTE V_SQL INTO V_SEQUENCE;

IF(COALESCE(V_A_END_ENTITY_TYPE,'')='' OR COALESCE(V_B_END_ENTITY_TYPE,'')='')
THEN
V_STATUS=FALSE;
END IF;

IF(V_A_END_ENTITY_TYPE!=V_B_END_ENTITY_TYPE)
THEN
IF(UPPER(V_A_END_ENTITY_TYPE)='MANHOLE')
THEN
SELECT CASE WHEN MANHOLE_TYPES='TC2' THEN 'LM002' ELSE V_CHAMBER_T END INTO V_B_END_CODE FROM ATT_DETAILS_MANHOLE WHERE SYSTEM_ID=V_A_END_SYSTEM_ID;
ELSIF (UPPER(V_B_END_ENTITY_TYPE)='MANHOLE')
THEN
SELECT CASE WHEN MANHOLE_TYPES='TC2' THEN 'LM002' ELSE V_CHAMBER_T END INTO V_B_END_CODE FROM ATT_DETAILS_MANHOLE WHERE SYSTEM_ID=V_B_END_SYSTEM_ID;
END IF;
END IF;

V_SQL='SELECT CASE WHEN UPPER(OWNERSHIP_TYPE)=''OWN'' THEN ''OB'' ELSE ''TP'' END FROM '|| V_LAYER_TABLE ||' WHERE SYSTEM_ID='|| P_SYSTEM_ID ||'';
--RAISE INFO'V_SQL %',V_SQL;
EXECUTE V_SQL INTO V_BUILD_TYPE;

V_SQL='SELECT VM.ABBR FROM '|| V_LAYER_TABLE ||' ATT INNER JOIN VENDOR_MASTER VM ON UPPER(REPLACE(ATT.OWNERSHIP_TYPE,'' '',''''))=UPPER(VM.TYPE)
AND VM.ID=' || CASE WHEN V_BUILD_TYPE='OB' then 'ATT.OWN_VENDOR_ID::INTEGER' else 'ATT.THIRD_PARTY_VENDOR_ID' END ||' WHERE ATT.SYSTEM_ID='|| P_SYSTEM_ID ||'' ;
--RAISE INFO'V_SQL %',V_SQL;
EXECUTE V_SQL INTO V_BUILD_BY;

IF(COALESCE(V_SEQUENCE,0)!=0 AND COALESCE(V_CICRCLE_CODE,'')!='' AND COALESCE(V_ENTITY_CODE,'')!='' AND COALESCE(V_BUILD_TYPE,'')!='' AND COALESCE(V_BUILD_BY,'')!=''
AND COALESCE(V_ENTITY_T,'')!='' AND COALESCE(V_A_END_CODE,'')!='' AND COALESCE(V_B_END_CODE,'')!='')
THEN
V_ROUTE_ID=V_ENTITY_CODE||'_'||V_CICRCLE_CODE||'_'||V_BUILD_TYPE||'_'||V_BUILD_BY||'_'||V_ENTITY_T||'_'||V_A_END_CODE||'_'||V_B_END_CODE||'_R'||V_SEQUENCE::TEXT;
ELSE
V_STATUS=FALSE;

END IF;

ELSE
IF(UPPER(P_ENTITY_TYPE)='FMS')
THEN
SELECT ST_BUFFER_METERS(SP_GEOMETRY,2) INTO V_STARTPOINT FROM POINT_MASTER WHERE UPPER(ENTITY_TYPE)=UPPER(P_ENTITY_TYPE) AND SYSTEM_ID=P_SYSTEM_ID;
--RAISE INFO'V_STARTPOINT %',V_STARTPOINT;
SELECT SUBSTRING(GIS_DESIGN_ID,4,CHAR_LENGTH (GIS_DESIGN_ID)-6) INTO V_DESIGN_ID FROM LINE_MASTER WHERE
ST_INTERSECTS(SP_GEOMETRY,V_STARTPOINT) AND UPPER(ENTITY_TYPE)='CABLE' AND COALESCE(GIS_DESIGN_ID,'')!='' LIMIT 1;
--RAISE INFO'V_DESIGN_ID %',V_DESIGN_ID;
ELSE
-- SELECT SUBSTRING(ATT.GIS_DESIGN_ID,4,CHAR_LENGTH (ATT.GIS_DESIGN_ID)-6) INTO V_DESIGN_ID FROM ASSOCIATE_ENTITY_INFO AI
-- INNER JOIN ATT_DETAILS_CABLE ATT ON AI.ASSOCIATED_SYSTEM_ID=ATT.SYSTEM_ID AND UPPER(AI.ASSOCIATED_ENTITY_TYPE)='CABLE' AND
-- AI.ENTITY_SYSTEM_ID=P_SYSTEM_ID AND UPPER(AI.ENTITY_TYPE)=UPPER(P_ENTITY_TYPE) AND COALESCE(ATT.GIS_DESIGN_ID,'')!='';

SELECT SUBSTRING(ATT.GIS_DESIGN_ID,4,CHAR_LENGTH (ATT.GIS_DESIGN_ID)-6) INTO V_DESIGN_ID FROM ATT_DETAILS_CABLE ATT
WHERE ATT.SYSTEM_ID=P_ASSOCIATE_SYSTEM_ID;

V_SQL='SELECT COUNT(1)+1 FROM '|| V_LAYER_TABLE ||' WHERE GIS_DESIGN_ID ILIKE ''%'|| V_DESIGN_ID ||'%''';
EXECUTE V_SQL INTO V_SEQUENCE;

END IF;

--RAISE INFO'V_SEQUENCE %',V_SEQUENCE;
IF(COALESCE(V_DESIGN_ID,'')!='')
THEN --V_CHAMBER_T
V_SQL='SELECT ' || CASE
WHEN UPPER(P_ENTITY_TYPE)='MANHOLE' THEN '''_''||MANHOLE_TYPES||''_''||CASE WHEN MANHOLE_TYPES=''TC2'' THEN ''LM002''||''_'' ELSE '''|| V_CHAMBER_T ||'''||''_'' END'
WHEN UPPER(P_ENTITY_TYPE)='SPLICECLOSURE' THEN '''_'''
WHEN UPPER(P_ENTITY_TYPE)='FMS' THEN '''_''||INSTALLATION_LOCATION_CODE||''_''||FMS_TYPE||''_0''||NO_OF_PORT::TEXT'
WHEN UPPER(P_ENTITY_TYPE)='POLE' THEN '''_''' END ||'
FROM '|| V_LAYER_TABLE ||' WHERE SYSTEM_ID='|| P_SYSTEM_ID ||'';
--RAISE INFO'V_SQL %',V_SQL;
EXECUTE V_SQL INTO V_ENTITY_T;

IF(UPPER(P_ENTITY_TYPE)='FMS')
THEN
IF(COALESCE(V_ENTITY_CODE,'')!='' AND COALESCE(V_ENTITY_T,'')!='')
THEN
V_ROUTE_ID=V_ENTITY_CODE||'_'||V_DESIGN_ID||V_ENTITY_T;
--RAISE INFO'V_ROUTE_ID %',V_ROUTE_ID;
ELSE
V_STATUS=FALSE;
END IF;
ELSE
IF(COALESCE(V_SEQUENCE,0)!=0 AND COALESCE(V_ENTITY_CODE,'')!='' AND COALESCE(V_ENTITY_T,'')!='')
THEN
V_ROUTE_ID=V_ENTITY_CODE||'_'||V_DESIGN_ID||V_ENTITY_T||(select LPAD(V_SEQUENCE::TEXT, 3, '0'));
ELSE
V_STATUS=FALSE;
END IF;
END IF;

ELSE
V_STATUS=FALSE;
END IF;
END IF;
IF(V_STATUS)
THEN
IF(UPPER(P_ENTITY_TYPE)!='FMS')
THEN
V_SQL='UPDATE '|| V_LAYER_TABLE ||' SET GIS_DESIGN_ID='''|| V_ROUTE_ID ||''',CODIFICATION_SEQUENCE='|| V_SEQUENCE ||' WHERE SYSTEM_ID='|| P_SYSTEM_ID ||'';
--RAISE INFO'V_SQL %',V_SQL;
EXECUTE V_SQL;
ELSE
V_SQL='UPDATE '|| V_LAYER_TABLE ||' SET GIS_DESIGN_ID='''|| V_ROUTE_ID ||''' WHERE SYSTEM_ID='|| P_SYSTEM_ID ||'';
--RAISE INFO'V_SQL %',V_SQL;
EXECUTE V_SQL;
END IF;
V_SQL='UPDATE '|| V_GEOM_TABLE ||' SET GIS_DESIGN_ID='''|| V_ROUTE_ID ||''',DISPLAY_NAME='''|| V_ROUTE_ID ||''' WHERE SYSTEM_ID='|| P_SYSTEM_ID ||'
AND UPPER(ENTITY_TYPE)=UPPER('''|| P_ENTITY_TYPE ||''')';
EXECUTE V_SQL;
END IF;
END IF;

RETURN QUERY SELECT V_STATUS::BOOLEAN AS STATUS,V_ROUTE_ID::CHARACTER VARYING AS ROUTEID;
END;
$BODY$;




CREATE OR REPLACE FUNCTION PUBLIC.FN_CREATE_CABLE_ASSOCIATED_ROUTE_ID(
	P_SYSTEM_ID INTEGER,P_ENTITY_TYPE CHARACTER VARYING)
    RETURNS TABLE(STATUS BOOLEAN, MESSAGE CHARACTER VARYING) 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$

DECLARE
V_STATUS BOOLEAN=TRUE; 
V_MESSAGE CHARACTER VARYING;
V_ASSOCIATE_SYSTEM_ID INTEGER;
V_ASSOCIATE_ENTITY_TYPE CHARACTER VARYING;
V_STARTPOINT GEOMETRY;
V_ENDPOINT GEOMETRY;
V_ROW RECORD;
BEGIN

CREATE TEMP TABLE TEMP_ENTITES
(
  SYSTEM_ID INTEGER NULL,
  ENTITY_TYPE CHARACTER VARYING(30)
)ON COMMIT DROP ; 

SELECT ST_BUFFER_METERS(ST_STARTPOINT(SP_GEOMETRY),2) INTO V_STARTPOINT FROM LINE_MASTER WHERE UPPER(ENTITY_TYPE)=UPPER(P_ENTITY_TYPE) AND SYSTEM_ID=P_SYSTEM_ID;
SELECT ST_BUFFER_METERS(ST_ENDPOINT(SP_GEOMETRY),2) INTO V_ENDPOINT FROM LINE_MASTER WHERE UPPER(ENTITY_TYPE)=UPPER(P_ENTITY_TYPE) AND SYSTEM_ID=P_SYSTEM_ID;

INSERT INTO TEMP_ENTITES (SYSTEM_ID,ENTITY_TYPE)
SELECT ASSOCIATED_SYSTEM_ID,ASSOCIATED_ENTITY_TYPE FROM ASSOCIATE_ENTITY_INFO where ENTITY_SYSTEM_ID=P_SYSTEM_ID and ENTITY_TYPE=P_ENTITY_TYPE 
AND UPPER(ASSOCIATED_ENTITY_TYPE) IN ('POLE','MANHOLE','SPLICECLOSURE','DUCT');

INSERT INTO TEMP_ENTITES (SYSTEM_ID,ENTITY_TYPE)
SELECT ENTITY_SYSTEM_ID,ENTITY_TYPE FROM ASSOCIATE_ENTITY_INFO where ASSOCIATED_SYSTEM_ID=P_SYSTEM_ID and ASSOCIATED_ENTITY_TYPE=P_ENTITY_TYPE 
AND UPPER(ENTITY_TYPE) IN ('POLE','MANHOLE','SPLICECLOSURE','DUCT');

INSERT INTO TEMP_ENTITES (SYSTEM_ID,ENTITY_TYPE)
SELECT ENTITY_SYSTEM_ID,ENTITY_TYPE FROM ASSOCIATE_ENTITY_INFO WHERE ASSOCIATED_SYSTEM_ID IN (SELECT SYSTEM_ID FROM TEMP_ENTITES WHERE UPPER(ENTITY_TYPE)='DUCT') AND UPPER(ASSOCIATED_ENTITY_TYPE)='DUCT' AND UPPER(ENTITY_TYPE)='TRENCH'; 

INSERT INTO TEMP_ENTITES (SYSTEM_ID,ENTITY_TYPE)
SELECT ASSOCIATED_SYSTEM_ID,ASSOCIATED_ENTITY_TYPE FROM ASSOCIATE_ENTITY_INFO WHERE ENTITY_SYSTEM_ID IN (SELECT SYSTEM_ID FROM TEMP_ENTITES WHERE UPPER(ENTITY_TYPE)='DUCT') AND UPPER(ENTITY_TYPE)='DUCT' AND UPPER(ASSOCIATED_ENTITY_TYPE)='TRENCH'; 


INSERT INTO TEMP_ENTITES (SYSTEM_ID,ENTITY_TYPE)
SELECT ENTITY_SYSTEM_ID,ENTITY_TYPE FROM ASSOCIATE_ENTITY_INFO WHERE ASSOCIATED_SYSTEM_ID IN (SELECT SYSTEM_ID FROM TEMP_ENTITES WHERE UPPER(ENTITY_TYPE)='MANHOLE') AND UPPER(ASSOCIATED_ENTITY_TYPE)='MANHOLE' AND UPPER(ENTITY_TYPE)='SPLICECLOSURE'; 

INSERT INTO TEMP_ENTITES (SYSTEM_ID,ENTITY_TYPE)
SELECT ASSOCIATED_SYSTEM_ID,ASSOCIATED_ENTITY_TYPE FROM ASSOCIATE_ENTITY_INFO WHERE ENTITY_SYSTEM_ID IN (SELECT SYSTEM_ID FROM TEMP_ENTITES WHERE UPPER(ENTITY_TYPE)='MANHOLE') AND UPPER(ENTITY_TYPE)='MANHOLE' AND UPPER(ASSOCIATED_ENTITY_TYPE)='SPLICECLOSURE'; 


INSERT INTO TEMP_ENTITES (SYSTEM_ID,ENTITY_TYPE)
SELECT SYSTEM_ID,ENTITY_TYPE FROM POINT_MASTER WHERE
ST_INTERSECTS(SP_GEOMETRY,V_STARTPOINT) AND UPPER(ENTITY_TYPE)='FMS';

INSERT INTO TEMP_ENTITES (SYSTEM_ID,ENTITY_TYPE)
SELECT SYSTEM_ID,ENTITY_TYPE FROM POINT_MASTER WHERE
ST_INTERSECTS(SP_GEOMETRY,V_ENDPOINT) AND UPPER(ENTITY_TYPE)='FMS';

PERFORM (FN_CREATE_ROUTE_ID(P_SYSTEM_ID,P_ENTITY_TYPE,0,''));

IF V_STATUS
THEN
	V_MESSAGE='Section Id created successfully !';
	
	FOR V_ROW IN SELECT DISTINCT SYSTEM_ID,ENTITY_TYPE FROM TEMP_ENTITES
	LOOP
		RAISE INFO'V_ROW.SYSTEM_ID %',V_ROW.SYSTEM_ID;
		RAISE INFO'V_ROW.ENTITY_TYPE %',V_ROW.ENTITY_TYPE;
		PERFORM (FN_CREATE_ROUTE_ID(V_ROW.SYSTEM_ID,V_ROW.ENTITY_TYPE,P_SYSTEM_ID,P_ENTITY_TYPE));
	END LOOP;
ELSE
	V_MESSAGE='Section Id creation failed !';
END IF;

RETURN QUERY SELECT V_STATUS::BOOLEAN AS STATUS,V_MESSAGE::CHARACTER VARYING AS MESSAGE;
END;
$BODY$;