--drop VIEW public.vw_att_details_fault

CREATE OR replace VIEW public.vw_att_details_fault
AS SELECT flt.system_id,
    flt.network_id,
    flt.fault_id,
    round(flt.latitude::numeric, 6) AS latitude,
    round(flt.longitude::numeric, 6) AS longitude,
    flt.province_id,
    flt.region_id,
    flt.fault_type,
    flt.fault_entity_system_id,
    flt.fault_entity_type,
    flt.fault_entity_network_id,
    flt.fault_reason,
    flt.fault_ticket_type,
    flt.fault_ticket_id,
    flt.parent_system_id,
    flt.parent_entity_type,
    flt.parent_network_id,
    flt.remarks,
    flt.fault_status,
    flt.status,
    flt.network_status,
    flt.business_type,
    flt.created_by,
    fn_get_date(flt.created_on) AS created_date,
    um2.user_id AS modified_by,
    fn_get_date(flt.modified_on) AS modified_date,
    flt.status_remark,
    flt.status_updated_by,
    flt.status_updated_on,
    flt.is_visible_on_map,
    flt.source_ref_type,
    flt.source_ref_id,
    flt.source_ref_description,
    flt.primary_pod_system_id,
    flt.secondary_pod_system_id,
    flt.is_new_entity,
    flt.origin_from,
    flt.origin_ref_id,
    flt.origin_ref_code,
    flt.origin_ref_description,
    flt.request_ref_id,
    flt.requested_by,
    flt.request_approved_by,
    flt.subarea_id,
    flt.area_id,
    flt.dsa_id,
    flt.csa_id,
    reg.region_name,
    prov.province_name,
    flt.gis_design_id,
    flt.st_x,
    flt.st_y,
    flt.ne_id,
    flt.prms_id,
    flt.jc_id,
    flt.mzone_id
   FROM att_details_fault flt
     JOIN province_boundary prov ON flt.province_id = prov.id
     JOIN region_boundary reg ON flt.region_id = reg.id
     JOIN user_master um ON flt.created_by = um.user_id
     LEFT JOIN user_master um2 ON flt.modified_by = um2.user_id;