//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartInventoryServices.ConvergeERPService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvIssueDtl", Namespace="http://schemas.datacontract.org/2004/07/CICT_INV_Maintenance")]
    [System.SerializableAttribute()]
    public partial class InvIssueDtl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ItemCodeField;
        
        private double QuantityField;
        
        private string SerialField;
        
        private string UOMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialField, value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UOM {
            get {
                return this.UOMField;
            }
            set {
                if ((object.ReferenceEquals(this.UOMField, value) != true)) {
                    this.UOMField = value;
                    this.RaisePropertyChanged("UOM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvReturn", Namespace="http://schemas.datacontract.org/2004/07/CICT_INV_Maintenance")]
    [System.SerializableAttribute()]
    public partial class InvReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ItemCodeField;
        
        private double QuantityField;
        
        private string SerialField;
        
        private string UOMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Serial {
            get {
                return this.SerialField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialField, value) != true)) {
                    this.SerialField = value;
                    this.RaisePropertyChanged("Serial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UOM {
            get {
                return this.UOMField;
            }
            set {
                if ((object.ReferenceEquals(this.UOMField, value) != true)) {
                    this.UOMField = value;
                    this.RaisePropertyChanged("UOM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConvergeERPService.I_ERP_Service")]
    public interface I_ERP_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ERP_Service/CreateInvIssue", ReplyAction="http://tempuri.org/I_ERP_Service/CreateInvIssueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/I_ERP_Service/CreateInvIssueStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        string CreateInvIssue(string TranNo, string Bundle, string Technology, string Location, string WHCode, SmartInventoryServices.ConvergeERPService.InvIssueDtl[] Dtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ERP_Service/CreateInvIssue", ReplyAction="http://tempuri.org/I_ERP_Service/CreateInvIssueResponse")]
        System.Threading.Tasks.Task<string> CreateInvIssueAsync(string TranNo, string Bundle, string Technology, string Location, string WHCode, SmartInventoryServices.ConvergeERPService.InvIssueDtl[] Dtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ERP_Service/CreateInvReturn", ReplyAction="http://tempuri.org/I_ERP_Service/CreateInvReturnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/I_ERP_Service/CreateInvReturnStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        string CreateInvReturn(string TranNo, string WHCode, SmartInventoryServices.ConvergeERPService.InvReturn[] Dtl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_ERP_Service/CreateInvReturn", ReplyAction="http://tempuri.org/I_ERP_Service/CreateInvReturnResponse")]
        System.Threading.Tasks.Task<string> CreateInvReturnAsync(string TranNo, string WHCode, SmartInventoryServices.ConvergeERPService.InvReturn[] Dtl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_ERP_ServiceChannel : SmartInventoryServices.ConvergeERPService.I_ERP_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_ERP_ServiceClient : System.ServiceModel.ClientBase<SmartInventoryServices.ConvergeERPService.I_ERP_Service>, SmartInventoryServices.ConvergeERPService.I_ERP_Service {
        
        public I_ERP_ServiceClient() {
        }
        
        public I_ERP_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_ERP_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_ERP_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_ERP_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateInvIssue(string TranNo, string Bundle, string Technology, string Location, string WHCode, SmartInventoryServices.ConvergeERPService.InvIssueDtl[] Dtl) {
            return base.Channel.CreateInvIssue(TranNo, Bundle, Technology, Location, WHCode, Dtl);
        }
        
        public System.Threading.Tasks.Task<string> CreateInvIssueAsync(string TranNo, string Bundle, string Technology, string Location, string WHCode, SmartInventoryServices.ConvergeERPService.InvIssueDtl[] Dtl) {
            return base.Channel.CreateInvIssueAsync(TranNo, Bundle, Technology, Location, WHCode, Dtl);
        }
        
        public string CreateInvReturn(string TranNo, string WHCode, SmartInventoryServices.ConvergeERPService.InvReturn[] Dtl) {
            return base.Channel.CreateInvReturn(TranNo, WHCode, Dtl);
        }
        
        public System.Threading.Tasks.Task<string> CreateInvReturnAsync(string TranNo, string WHCode, SmartInventoryServices.ConvergeERPService.InvReturn[] Dtl) {
            return base.Channel.CreateInvReturnAsync(TranNo, WHCode, Dtl);
        }
    }
}
