//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartInventoryServices.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://zato.io/ns/20130518", ConfigurationName="WebService.ConvergeERP")]
    public interface ConvergeERP {
        
        // CODEGEN: Generating message contract since the operation createInvReturn is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="createInvReturn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SmartInventoryServices.WebService.createInvReturnResponse1 createInvReturn(SmartInventoryServices.WebService.createInvReturn1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="createInvReturn", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartInventoryServices.WebService.createInvReturnResponse1> createInvReturnAsync(SmartInventoryServices.WebService.createInvReturn1 request);
        
        // CODEGEN: Generating message contract since the operation createInvIssue is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="createInvIssue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SmartInventoryServices.WebService.createInvIssueResponse1 createInvIssue(SmartInventoryServices.WebService.createInvIssue1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="createInvIssue", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartInventoryServices.WebService.createInvIssueResponse1> createInvIssueAsync(SmartInventoryServices.WebService.createInvIssue1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://zato.io/ns/20130518")]
    public partial class createInvReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CreateInvRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public CreateInvRequest request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("request");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://zato.io/ns/20130518")]
    public partial class CreateInvRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tranNoField;
        
        private string wHCodeField;
        
        private InventoryItem[] dtlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TranNo {
            get {
                return this.tranNoField;
            }
            set {
                this.tranNoField = value;
                this.RaisePropertyChanged("TranNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WHCode {
            get {
                return this.wHCodeField;
            }
            set {
                this.wHCodeField = value;
                this.RaisePropertyChanged("WHCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public InventoryItem[] Dtl {
            get {
                return this.dtlField;
            }
            set {
                this.dtlField = value;
                this.RaisePropertyChanged("Dtl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://zato.io/ns/20130518")]
    public partial class InventoryItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemCodeField;
        
        private string serialField;
        
        private string uOMField;
        
        private double quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
                this.RaisePropertyChanged("ItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://zato.io/ns/20130518")]
    public partial class createInvIssueResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Response createInvIssueResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Response createInvIssueResult {
            get {
                return this.createInvIssueResultField;
            }
            set {
                this.createInvIssueResultField = value;
                this.RaisePropertyChanged("createInvIssueResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://zato.io/ns/20130518")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error[] errorsField;
        
        private object outField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public Error[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public object @out {
            get {
                return this.outField;
            }
            set {
                this.outField = value;
                this.RaisePropertyChanged("out");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://zato.io/ns/20130518")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://zato.io/ns/20130518")]
    public partial class createInvIssue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CreateInvRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public CreateInvRequest request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("request");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://zato.io/ns/20130518")]
    public partial class createInvReturnResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Response createInvReturnResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Response createInvReturnResult {
            get {
                return this.createInvReturnResultField;
            }
            set {
                this.createInvReturnResultField = value;
                this.RaisePropertyChanged("createInvReturnResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createInvReturn1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://zato.io/ns/20130518", Order=0)]
        public SmartInventoryServices.WebService.createInvReturn createInvReturn;
        
        public createInvReturn1() {
        }
        
        public createInvReturn1(SmartInventoryServices.WebService.createInvReturn createInvReturn) {
            this.createInvReturn = createInvReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createInvReturnResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://zato.io/ns/20130518", Order=0)]
        public SmartInventoryServices.WebService.createInvReturnResponse createInvReturnResponse;
        
        public createInvReturnResponse1() {
        }
        
        public createInvReturnResponse1(SmartInventoryServices.WebService.createInvReturnResponse createInvReturnResponse) {
            this.createInvReturnResponse = createInvReturnResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createInvIssue1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://zato.io/ns/20130518", Order=0)]
        public SmartInventoryServices.WebService.createInvIssue createInvIssue;
        
        public createInvIssue1() {
        }
        
        public createInvIssue1(SmartInventoryServices.WebService.createInvIssue createInvIssue) {
            this.createInvIssue = createInvIssue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createInvIssueResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://zato.io/ns/20130518", Order=0)]
        public SmartInventoryServices.WebService.createInvIssueResponse createInvIssueResponse;
        
        public createInvIssueResponse1() {
        }
        
        public createInvIssueResponse1(SmartInventoryServices.WebService.createInvIssueResponse createInvIssueResponse) {
            this.createInvIssueResponse = createInvIssueResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvergeERPChannel : SmartInventoryServices.WebService.ConvergeERP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvergeERPClient : System.ServiceModel.ClientBase<SmartInventoryServices.WebService.ConvergeERP>, SmartInventoryServices.WebService.ConvergeERP {
        
        public ConvergeERPClient() {
        }
        
        public ConvergeERPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvergeERPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvergeERPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvergeERPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartInventoryServices.WebService.createInvReturnResponse1 SmartInventoryServices.WebService.ConvergeERP.createInvReturn(SmartInventoryServices.WebService.createInvReturn1 request) {
            return base.Channel.createInvReturn(request);
        }
        
        public SmartInventoryServices.WebService.createInvReturnResponse createInvReturn(SmartInventoryServices.WebService.createInvReturn createInvReturn1) {
            SmartInventoryServices.WebService.createInvReturn1 inValue = new SmartInventoryServices.WebService.createInvReturn1();
            inValue.createInvReturn = createInvReturn1;
            SmartInventoryServices.WebService.createInvReturnResponse1 retVal = ((SmartInventoryServices.WebService.ConvergeERP)(this)).createInvReturn(inValue);
            return retVal.createInvReturnResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartInventoryServices.WebService.createInvReturnResponse1> SmartInventoryServices.WebService.ConvergeERP.createInvReturnAsync(SmartInventoryServices.WebService.createInvReturn1 request) {
            return base.Channel.createInvReturnAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartInventoryServices.WebService.createInvReturnResponse1> createInvReturnAsync(SmartInventoryServices.WebService.createInvReturn createInvReturn) {
            SmartInventoryServices.WebService.createInvReturn1 inValue = new SmartInventoryServices.WebService.createInvReturn1();
            inValue.createInvReturn = createInvReturn;
            return ((SmartInventoryServices.WebService.ConvergeERP)(this)).createInvReturnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartInventoryServices.WebService.createInvIssueResponse1 SmartInventoryServices.WebService.ConvergeERP.createInvIssue(SmartInventoryServices.WebService.createInvIssue1 request) {
            return base.Channel.createInvIssue(request);
        }
        
        public SmartInventoryServices.WebService.createInvIssueResponse createInvIssue(SmartInventoryServices.WebService.createInvIssue createInvIssue1) {
            SmartInventoryServices.WebService.createInvIssue1 inValue = new SmartInventoryServices.WebService.createInvIssue1();
            inValue.createInvIssue = createInvIssue1;
            SmartInventoryServices.WebService.createInvIssueResponse1 retVal = ((SmartInventoryServices.WebService.ConvergeERP)(this)).createInvIssue(inValue);
            return retVal.createInvIssueResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartInventoryServices.WebService.createInvIssueResponse1> SmartInventoryServices.WebService.ConvergeERP.createInvIssueAsync(SmartInventoryServices.WebService.createInvIssue1 request) {
            return base.Channel.createInvIssueAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartInventoryServices.WebService.createInvIssueResponse1> createInvIssueAsync(SmartInventoryServices.WebService.createInvIssue createInvIssue) {
            SmartInventoryServices.WebService.createInvIssue1 inValue = new SmartInventoryServices.WebService.createInvIssue1();
            inValue.createInvIssue = createInvIssue;
            return ((SmartInventoryServices.WebService.ConvergeERP)(this)).createInvIssueAsync(inValue);
        }
    }
}
