# author: hari-lepton
# date: 17-Feb-2024
name: Test | Build and publish on PR merge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  #pull_request:
    #branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-2019]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Restore NuGet packages
        run: nuget restore Source/SmartInventory/SmartInventory.sln
        
      # - name: Build the solution
      #   run: msbuild Source/SmartInventory/SmartInventory.sln /p:Configuration=Release

      - name: Build SmartInventory Web
        run: msbuild Source/SmartInventory/SmartInventory/SmartInventory.csproj /p:Configuration=Release /t:Publish /p:PublishProfile=FolderProfileWeb.pubxml

      - name: List contents of bin directory
        run: ls -R Source/SmartInventory/SmartInventory/bin

      - name: Publish SmartInventory Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SmartInventory_Web
          path: 'Source/SmartInventory/SmartInventory/bin/app.publish'
      
      # - name: Build SmartInventory Services
      #   run: msbuild Source/SmartInventory/SmartInventoryServices/SmartInventoryServices.csproj /p:Configuration=Release /t:Publish

      # - name: Publish SmartInventory Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: SmartInventory_Services
      #     path: 'Source/SmartInventory/SmartInventoryServices/bin'
